### ISSUE TITLE
信息处理思考

### ISSUE THREAD

**Issue by xiang578** [xiang578/xiang578.github.io#10]
材料 - 信息 - 知识

**Comment by JimmyLv** [comment]
wow~ ⊙o⊙ 首先，看到你的 repo 感觉好开心，😊

再推荐给你这个现有的 DIKW 模型：

![image](https://user-images.githubusercontent.com/4997466/39289197-ad0c5402-495d-11e8-9f83-70d749c1fc79.png)

![image](https://user-images.githubusercontent.com/4997466/39289221-bd7b0fe0-495d-11e8-8bfd-a79b9e2e4eac.png)

![image](https://user-images.githubusercontent.com/4997466/39289224-c0e6c8a4-495d-11e8-81c1-b74f2f1eeb22.png)

**Comment by xiang578** [comment]
@JimmyLv 
感谢提供参考资料，利用 issue 公开管理一些项目也是从你的 repo 中学习的，第一次看到这种方法，真是醍醐灌顶。
