### ISSUE TITLE
纯文本任务管理思考

### ISSUE THREAD

**Issue by xiang578** [xiang578/xiang578.github.io#11]
### ⓵ 定义目标和原则

终极目的

Q：为什么你要花时间来做这项任务，而不是其他随便什么任务？
A：

### ⓶ 展望结果（OKRs）

利益相关人清单

Q：当你交付最终结果的时候，会如何让世界变得更好？
A：

### ⓹ 明确「下一步行动」

能够产生反馈结果的小任务

**Comment by xiang578** [comment]
Mac: [TaskPaper](https://www.taskpaper.com/) or [PlainTask-sublime](https://github.com/aziz/PlainTasks)
iOS: Editorial

## 实践
- 每天安排 3 个主要任务 + 一个 log
- log 中记录今天完成的其他事情。
![image](https://user-images.githubusercontent.com/12624910/38538208-463f000c-3cc5-11e8-9f6d-c6a37b0a660d.png)


## 参考
- [完全用纯文本工作丨2016 与我的数字生活 - 少数派](https://sspai.com/post/37086)
- [《18分钟》：如何用18分钟变身效率达人？| 狗熊月读64_哔哩哔哩 (゜-゜)つロ 干杯~-bilibili](https://www.bilibili.com/video/av18698116)
- [重回纯文本，兼谈电子化时代 GUI 工具的弊端与反思 GTD · Issue #288 · JimmyLv/jimmylv.github.io](https://github.com/JimmyLv/jimmylv.github.io/issues/288)
- [从终端到纯文本：我的任务管理简史 - 少数派](https://sspai.com/post/62497)
- [我的时间管理工具 · 构建我的被动收入](https://www.bmpi.dev/self/gtd-tools-i-used/)
- [构建个人知识体系 · 构建我的被动收入](https://www.bmpi.dev/self/build-personal-knowledge-system/)

**Comment by xiang578** [comment]
[aziz/PlainTasks: An opinionated todo-list plugin for Sublime Text editor (version 2 and 3)](https://github.com/aziz/PlainTasks)
## 快捷键
- `⌘ + enter` or `⌘ + i` : 新任务
- 光标停留在 tags 上，按鼠标右键，Filter by tags under cursors过滤出有这个 tag 的任务，还原 ⌘+k，⌘+j
- ⌘+shift+r 标签导航
- `--` and then `tab` will get `--- ✄ -----------------------`
- 特殊标签（敲第一个字母然后在按tab）：@today @critical @high @low @started
- 时间相关：开始时间`s+tab+tab` 暂停 `tg+tab+tab` 当前时间`cr+tab+tab` 
- 日期 `d`+`tab` @due()
- 支持文件格式，以及使用 `ctrl+o` 在 sublime 中打开文件
- `Tasks: View as HTML` 以网页形式查看
- `⌘+r` 项目中跳转
- `⌘+shift+r` 标签中跳转


[bevesce/todoflow_sublime: Plain text to-do list plugin for Sublime Text 3](https://github.com/bevesce/todoflow_sublime)
- 检索的语法同 taskpaper 
- `filter` 检索当前文件
- `saved_filters` 根据已经保存的检索语句检索
- `move_to_project` 移动任务 

[jonathandelgado/SublimeTodoReview: A SublimeText plugin for reviewing todo (and other) comments within your code.](https://github.com/jonathandelgado/SublimeTodoReview)

**Comment by xiang578** [comment]
[《18分钟》：如何用18分钟变身效率达人？| 狗熊月读64_哔哩哔哩 (゜-゜)つロ 干杯~-bilibili](https://www.bilibili.com/video/av18698116)

## 18分钟原则：3个步骤，一天的轻重缓急

- 【早上】5分钟：计划理清
	- 订出计划，理清在5个焦点领域确实可达成的事
- 【白天】8分钟：暂停觉察
	- 工作每1小时暂停一下，利用1分钟问自己：“我正在做此刻该做的事情吗”
- 【晚上】5分钟：回顾反思
	- 忙完一天，回顾反思，今天过得如何，什么行得通，什么行不通，明天该如何

## 狗熊实践
1. 年度 5 个关注维度
2. 每天列出5件事情，并作出一些前期估计，以及记录反思
3. 在文本环境中，英文输入较中文输入有巨大的优势（这就是目前学英语最大的动力吧）
![image](https://user-images.githubusercontent.com/12624910/38309588-0631f6e4-384d-11e8-9d6b-709e8a40c31a.png)

![image](https://user-images.githubusercontent.com/12624910/38309979-f47379ea-384d-11e8-9c23-a1b1c52e4a2d.png)

**Comment by xiang578** [comment]
## 3 things
1. 根据二八原则，我们应该将 80% 的精力投入到 20% 的关键事情中。每周、每天的三件事，保证我们不偏离这一个原则。
2. 要求：
    1. 黑白分明，三件事系统聚焦关键的事情，GTD系统处理日常、例行任务。
    2. 动词开头，参考 GTD 中的下一步动作概念，制定的事情可以执行。
    3. 结果明确，需要做出什么样的成果
    4. 预估时间，番茄工作法
3. 流程：周回顾时，制定下周三件事，初期不需要对周任务计划有较强的预估计能力。每天 Golden 10 时，制定明天三件事，并进行排序。做到第二天醒来，可以直接按照计划去做事。
4. 执行：根据 GTD 的理论，达到从头到尾、逐一处理、不避不拖、一次一事的境界。

![image](https://user-images.githubusercontent.com/12624910/38419139-d4719bf6-39d1-11e8-9341-aa8c2662938f.png)

**Comment by xiang578** [comment]
## 项目管理

### 思路

- 使用 Github Issues 管理项目，配合一系列软件提高使用体验
- Issues 克制，不同时进行多项，只看 Assignee 的项
- 周回顾时整理本周项目，关闭完成的，并修改相关的父级项目状态，保证每周选择的项目都有推进
- 子项目没有完成时，不对父项目进行分配
- 项目标签克制 紧急 重要 博客素材
- 预估计项目的 Story Point，统计项目完成的时间
- 结合 toggl 使用，toggl 中的描述使用项目名，分类里面不要使用（存在 # ，然而 # 在 toggl 中是标签的开始符号

### [gissues](https://github.com/divinites/gissues)
- 在配置文件中调整 `"syntax": "Packages/Plaintasks/PlainTasks.sublime-syntax"`，可以以 Plaintasks 的格式打开 issues
- Sublime Text 中直接打开项目所在的文件夹，利用 gissues 可以直接打开对应的 issues
https://github.com/bevesce/todoflow_sublime
https://github.com/jonathandelgado/SublimeTodoReview

### Zenhub
- 在 Github repo 中实现看板功能

### GitHawk
- iPhone 管理 Github 项目

### Issues template

- 创建 issues template 的方法：[Manually creating a single issue template for your repository - User Documentation](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/)
- hexo 博客中忽视渲染 issues template 的方法：[hexo设置skip_render,指定不进行渲染的文件 | 漂自己的移，让别人都撞墙去吧](http://www.gagahappy.com/hexo-set-skip-render/)

### Todo
  [ ] 项目大小的定义
  [ ] 如何协调 Github Issues 项目和 todoist 的关系
  [ ] Milestone 用法

**Comment by xiang578** [comment]
## 纯文本任务管理 Vs. GUI 软件

### 为什么不使用高级的任务管理软件
- omnifocus 某一刻突然发现自己买不起 iPhone 了
- todoist 网络太差，mac 上无法给客户端设置走 vpn
- 滴答清单 功能太少，感觉对于过滤的优先级太低
- 通病：任务管理软件注重任务管理，然而我希望能有方便的记录功能，而且可以自动集中在某个地方，方便每周回顾和归档
- 现实：关注的项目少，可以每天过一遍清单

### Taskpaper vs PlainTasks
- taskpaper 有强大的侧边栏，可以展示项目和过滤，实现快速聚焦。
- taskpaper 拖动任务异常的方便
- taskpaper 完成任务之后会有删除线的特效，看起来比较酷炫
- taskpaper 是付费软件。
- PlainTasks 有多个编辑器的插件，不过出了 sublime 貌似其他平台更新比较少
- PlainTasks 可以在 sublime 中使用，与其他记录的方式集中管理（evernote 插件 issues 插件）
- 任务文本保存为 md 文件，将任务符号修改成 `* [ ]`，相当于使用 markdown 管理任务，相对应通过 iCloud 同步，手机上也能进行轻量修改。
- 使用方法：之前考虑，利用这个管理软件来指定当日的工作重点内容，仔细一想这样子会造成内容的割裂，所以最好的方法是直接利用纯文本拆分项目
- 公司内的工作内容存在一个 work.md 文件中，个人项目通过 github issues 页面管理，将学习成长的过程展示出来。
- 滴答清单用来快速记录以及保存需要提醒的事项

### 优点
- 学习成本低
- 使用灵活

### 缺点
- 提醒不强大
- 跨平台管理不方便

* [ ] 在选择软件时，很少选择需要科学上网的软件，怕临时需要时不能得到，但是从自己目前情况来看一直使用自己的电脑和手机，根本没有遇到这种情况。@problem

**Comment by JimmyLv** [comment]
我直接把纯文本放在iCloud里面，所以都是跨平台跨设备同步的。

**Comment by xiang578** [comment]
>我直接把纯文本放在iCloud里面，所以都是跨平台跨设备同步的。

@JimmyLv 考虑过，不过ios没有找到合适的软件，taskmator不能自动同步iCloud文件

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JimmyLv** [comment]
@xiang578 直接用Files App就行了，配合iOS 12 的Siri Shortcut 还可以直接语音打开某个具体文件。

具体情况是，实测下来在手机端编辑的次数很少，更多只是查看，而编辑甚至都是伪需求。

### iOS 端的查看

我需要能在Spotlight里面能够直接搜索到文本，via [iOS Spotlight 调教指南 - 少数派](https://sspai.com/post/35818)

> 我所用的写作类 App 里 3，支持在 Spotlight 搜索的是 1Writer 和 Byword，两个都是标题搜索加全文搜索，所以只用其中一个就好。

需要做的就是让iOS端的应用打开的iCloud文件夹直接在mac上设置为Sublime所在的文件夹。

btw: 我没有用1Writer 或者 Byword，我还在用 [Letterspace](https://programmerbird.com/letterspace/)

### iOS 端的编辑

有很多原生支持 Files 的App可以直接打开Files的文本文件（注意不是 copy to XXX 复制一份再打开），而我用的就是Pretext（另一款是Textor）。

从需求上来说，手机端的编辑其实是很少的，所以够用就行啦。

--------------

以上都是从工具角度上来说的，而实际上更应该从需求出发，借鉴于采铜我也把输入分为三种：信息 - 灵感 - 作品，可以看看这篇：[基于「信息 - 灵感 - 作品」的写作输入工具集 · Issue #304 · JimmyLv/jimmylv.github.io](https://github.com/JimmyLv/jimmylv.github.io/issues/304)

在手机端来说，最主要需要被处理的其实是灵感，稍纵即逝，所以我选择的工具反而是 iOS 原生的「备忘录」。

**Comment by xiang578** [comment]
[robwalton/alfred-taskpaper-workflow: Alfred 3 workflow for TaskPaper](https://github.com/robwalton/alfred-taskpaper-workflow)

**Comment by JimmyLv** [comment]
我最近完全切到了 OmniFocus，真香！ https://github.com/JimmyLv/jimmylv.github.io/issues/348
