### ISSUE TITLE
十点关机

### ISSUE THREAD

**Issue by xiang578** [xiang578/xiang578.github.io#17]
- 2018-05-01 22:07 关机之后阅读《数学之美》
- 2018-05-02 忘记关机，继续调研

**Comment by xiang578** [comment]
早睡是不可能的，关键还是追求内心的宁静。

**Comment by JimmyLv** [comment]
我在床上就只玩iPad了，🤣 通常来说都是听博客、看书之类的，远离通讯App就是了。
