### ISSUE TITLE
每月分享 202003 | 算法花园

### ISSUE THREAD

**Issue by xiang578** [xiang578/xiang578.github.io#177]
https://xiang578.com/post/monthly-issue-202003.html 

 读书  呼吸 (豆瓣)：这是一本由 Byte.Coffee 主播 MilkShake 🐑 推荐的一本科幻小说集（前几天看其他东西的时候学会科幻小说的英文 sci-fi）。之前看到过，小说的价值在于作者用一个故事告诉你一个道理。最喜欢的是《商人和炼金术士之门》这篇：在传统的穿越小说无法改变未来和过去的基础上，论证穿越能更深刻理解生活。书中其他探讨的几个问题也很有价值，值得一读。  我看  徐大sa

**Comment by crossairplane** [comment]
哈哈，原来同是byte.coffee的听众

**Comment by xiang578** [comment]
> @crossairplane
> 哈哈，原来同是byte.coffee的听众

蛮喜欢羊老师的极简主义
