### ISSUE TITLE
Evernote

### ISSUE THREAD

**Issue by xiang578** [xiang578/xiang578.github.io#3]
## Evernote #3
- [x] 重新修改笔记本分类方式 @done (18-04-09 21:47)
- [x] 笔记本分类相关的博客 @article
- [x] 知识管理训练营相关的资料阅读
- [x] sublime 插件
- [x] 历史遗留笔记计划

**Comment by xiang578** [comment]
[divinites/gissues: A sublime text plug-in to manage GitHub repo issues](https://github.com/divinites/gissues): 能在本地以纯文本的方式管理 Github Issues
- `GitHub Issue: Show Open Issues`
- `GitHub Issue: Show All Issues`
- `GitHub Issue: Show Issue`
- `GitHub Issue: Create Issue`
- `GitHub Issue: post/update Issue`
- `GitHub Issue: close/reopen Issue`

**Comment by JimmyLv** [comment]
把 `"syntax": "Packages/Markdown/Markdown.sublime-syntax",` 设成 PlainTask 就更方便控制 TODO 了，😂

**Comment by xiang578** [comment]
@JimmyLv 
这个可以干什么？没有找到相关设置的方法？

**Comment by JimmyLv** [comment]
啊哈 gissues这个插件默认用的是Markdown语法，我是改成了PlainTask语法，从而可以直接用PlainTask这个插件了…

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xiang578** [comment]
@JimmyLv 
这个技巧真棒，解决我最近在思考的是使用 issues 管理项目还是使用plaintasks配合文件管理项目的问题。

再咨询你一个问题，每一次我用这个插件都需要输入仓库的名字，有没有办法保存常用的
![image](https://user-images.githubusercontent.com/12624910/42132194-f7cf6742-7d45-11e8-92cc-552ab92172d4.png)

**Comment by JimmyLv** [comment]
啊哈，我是在GitHub repo的文件夹里面去打开这个插件，所以直接就能打开。
