### ISSUE TITLE
减少 iPhone 的屏幕使用时间

### ISSUE THREAD

**Issue by xiang578** [xiang578/xiang578.github.io#43]
iOS 推出屏幕时间之后，感觉自己在上面花费的时间太多了，所以通过观察自己使用手机的规律，来减少每日的屏幕使用时间。

显然，在手机上减少的时间会在其他设备上增加，总的眼睛看屏幕时间不会减少，但是可以提高效率。

《Make Time》中提到一个观点：设备默认设置带来的干扰

**Comment by xiang578** [comment]
总的目标：每天使用时间控制在 90 分钟以内。

---
改进方向：
1. 每天早上醒的时候刷手机（微博、微信等）。立刻起来，洗脸刷牙，看书。
2. 工作间隙，打开手机看朋友圈。 反扣手机
3. 上下班路上减少看手机。上班路上看 kindle，下班路上听播客

改进方法：
1. 每天集中时间看微信、推特、inoreader 等，一次刷完，而不是多次打开。
2. 将部分功能转移到电脑上看。

**Comment by xiang578** [comment]
进展
- 0513-0518 **目标** 2 小时 实际

**Comment by JimmyLv** [comment]
哈哈哈哈，我最近也在改善生活状态，恢复健康和体重。

> 每天早上醒的时候刷手机（微博、微信等）。立刻起来，洗脸刷牙，看书。

我直接不带手机进卧室上床，在床上最多只能看iPad或者Kindle。 ref: https://github.com/JimmyLv/jimmylv.github.io/issues/350

> 工作间隙，打开手机看朋友圈。 反扣手机

在Habitica里面设置了奖惩机制，刷一次就得扣分，🤣

> 上下班路上看手机。上班看 kindle，下班听播客

上班的时候看Kindle是怎么做到的，看来工作量不饱和呀。

另外推荐一个手机App，横屏之后就开始翻页计时，ZenFlipClock

![image](https://user-images.githubusercontent.com/4997466/57820931-3c906400-77c1-11e9-90fa-c81f0e579082.png)

**Comment by xiang578** [comment]
@JimmyLv
- 上班的时候看Kindle是怎么做到的，看来工作量不饱和呀。
表述错误，上班路上看 kindle，下班路上听播客。

Get Habitica

**Comment by vulgur** [comment]
> 哈哈哈哈，我最近也在改善生活状态，恢复健康和体重。
> 
> > 每天早上醒的时候刷手机（微博、微信等）。立刻起来，洗脸刷牙，看书。
> 
> 我直接不带手机进卧室上床，在床上最多只能看iPad或者Kindle。 ref: [JimmyLv/jimmylv.github.io#350](https://github.com/JimmyLv/jimmylv.github.io/issues/350)
> 
> > 工作间隙，打开手机看朋友圈。 反扣手机
> 
> 在Habitica里面设置了奖惩机制，刷一次就得扣分，🤣
> 
> > 上下班路上看手机。上班看 kindle，下班听播客
> 
> 上班的时候看Kindle是怎么做到的，看来工作量不饱和呀。
> 
> 另外推荐一个手机App，横屏之后就开始翻页计时，ZenFlipClock
> 
> ![image](https://user-images.githubusercontent.com/4997466/57820931-3c906400-77c1-11e9-90fa-c81f0e579082.png)

感谢推荐极简时钟，我是这个 app 的开发者
